name: Keep Render SIO Server Awake

on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:

jobs:
  ping-server:
    runs-on: ubuntu-latest
    steps:
      - name: Curl ping endpoint
        run: curl -s https://doc-sugg-sio.onrender.com/ping